"""把模型写成 Abaqus 输入文件（.inp）。

对标脚本和 Abaqus 求解后端共用这一份实现——两处各写一份迟早会不一致。

两个关键决定：

**截面用 SECTION=GENERAL。** 直接给 A、I11、I12、I22、J，绕开截面形状换算的差异。

**局部坐标系显式给出 n1。** Abaqus 梁的局部 1 轴由数据行的方向余弦指定，
局部 2 轴 = t × n1。本程序的局部 y 取作 Abaqus 的 n1，于是 I11 = Iy、I22 = Iz。

.inp 全程保持 ASCII —— Abaqus 6.14 是 Python 2，非 ASCII 会引发编码问题。
"""

from __future__ import annotations

from pathlib import Path

import numpy as np

from frame3d import local_axes

DOF_NAMES = ("ux", "uy", "uz", "rx", "ry", "rz")


_LOAD_KEYS = ("nodal_loads", "member_loads", "member_spans", "settlements")


def _loads_of(model: dict, case: str | None) -> dict[str, list]:
    """取出该工况的全部荷载与支座沉降。

    一个 .inp 只写一个分析步，所以多工况模型必须显式指定取哪一个——
    默认悄悄取第一个会让人以为组合也算进去了。
    """
    cases = {str(c.get("name")): c for c in model.get("load_cases", [])}
    if case is not None:
        if case not in cases:
            raise KeyError(f"模型里没有名为 {case!r} 的工况，现有 {sorted(cases)}")
        chosen = cases[case]
    elif any(model.get(k) for k in _LOAD_KEYS) or not cases:
        chosen = model
    else:
        chosen = next(iter(cases.values()))
    return {k: list(chosen.get(k) or []) for k in _LOAD_KEYS}


def _uniform_spans(spans: list[dict]) -> list[dict]:
    """把 member_spans 里的均布项折成 member_loads 的写法。

    梯形与集中力这里一律拒绝，不做近似：Abaqus 的 *DLOAD 只支持沿单元均布，
    跨间集中力更是要求该处有节点。悄悄按等效均布导出去，两边算的就不是同一个
    模型了——而这一页的全部意义正是"两边算的是同一个模型"。
    """
    bad = sorted({str(e.get("kind")) for e in spans
                  if str(e.get("kind", "uniform")) != "uniform"})
    if bad:
        raise ValueError(
            f"Abaqus 导出暂不支持 {'、'.join(bad)} 杆间荷载："
            "*DLOAD 只能沿单元均布，跨间集中力还要求该位置有节点。"
            "把这类荷载改成节点荷载、或在荷载位置打断杆件之后再导出；"
            "自研求解器不受此限制。")
    return [{"member": e["member"], "w": e["w1"]} for e in spans]


def _fmt(x: float) -> str:
    return "%.10g" % float(x)


def write_inp(model: dict, element: str = "B33", path: Path | None = None,
              case: str | None = None) -> Path:
    """按模型写出一个 .inp。

    element 取 B33（Euler-Bernoulli，与本程序同一套理论）或 B31（Timoshenko）。
    case 指定取哪个荷载工况；留空则用顶层 nodal_loads / member_loads，
    没有顶层荷载时取 load_cases 的第一个。一个 .inp 只写一个分析步。
    """
    # 模型字典未必带 name（Session 里的模型就没有），退回一个中性名字
    name = "%s_%s" % (model.get("name", "model"), element)
    path = Path(path or f"{name}.inp")
    nodes = {int(n["id"]): n for n in model["nodes"]}
    sections = {s["name"]: s for s in model["sections"]}
    materials = {m["name"]: m for m in model["materials"]}

    L: list[str] = []
    L.append("*HEADING")
    L.append(" %s  element=%s  units=N-m-Pa"
             % (model.get("name", "model"), element))
    # .inp 全程保持 ASCII —— Abaqus 6.14 是 Python 2，中文注释会引发编码问题
    L.append("** generated by export_inp.py from the same model definition")
    L.append("*PREPRINT, ECHO=NO, MODEL=NO, HISTORY=NO")

    L.append("*NODE")
    for nid in sorted(nodes):
        n = nodes[nid]
        L.append(" %d, %s, %s, %s" % (nid, _fmt(n["x"]), _fmt(n["y"]), _fmt(n["z"])))

    # 每根杆件单独成 ELSET：截面方向 n1 逐根不同，必须逐根声明
    for m in model["members"]:
        L.append("*ELEMENT, TYPE=%s, ELSET=E%d" % (element, int(m["id"])))
        L.append(" %d, %d, %d" % (int(m["id"]), int(m["i"]), int(m["j"])))

    for m in model["members"]:
        sec = sections[m["section"]]
        pi = np.array([nodes[int(m["i"])][k] for k in "xyz"], dtype=float)
        pj = np.array([nodes[int(m["j"])][k] for k in "xyz"], dtype=float)
        _, rot = local_axes(pi, pj, tuple(m["ref_vector"]) if m.get("ref_vector") else None)
        n1 = rot[1]                      # 本程序局部 y 作为 Abaqus 的 n1
        L.append("*BEAM GENERAL SECTION, ELSET=E%d, SECTION=GENERAL, DENSITY=0."
                 % int(m["id"]))
        # A, I11, I12, I22, J   —— I11 对应绕局部 1（= 本程序 y）的惯性矩
        L.append(" %s, %s, 0., %s, %s" % (_fmt(sec["A"]), _fmt(sec["Iy"]),
                                          _fmt(sec["Iz"]), _fmt(sec["J"])))
        L.append(" %s, %s, %s" % (_fmt(n1[0]), _fmt(n1[1]), _fmt(n1[2])))
        mat = materials[m["material"]]
        L.append(" %s, %s" % (_fmt(mat["E"]), _fmt(mat["E"] / (2.0 * (1.0 + mat["nu"])))))

    L.append("*NSET, NSET=ALLN, GENERATE")
    L.append(" %d, %d, 1" % (min(nodes), max(nodes)))

    loads = _loads_of(model, case)
    mload = loads["member_loads"] + _uniform_spans(loads["member_spans"])
    cload = loads["nodal_loads"]
    given = {int(e["node"]): [float(v) for v in e["d"]] for e in loads["settlements"]}

    # 模型定义里只放零位移约束。带幅值的 *BOUNDARY 要写在分析步**里面**，
    # 写在外面是初始状态的一部分，含义不同
    L.append("*BOUNDARY")
    for sup in model["supports"]:
        for k, flag in enumerate(sup["fix"]):
            if flag:
                L.append(" %d, %d, %d" % (int(sup["node"]), k + 1, k + 1))

    # 给定位移不能放在线性摄动步里——摄动步的边界条件是相对基态的增量
    L.append("*STEP, NAME=STATIC" + ("" if given else ", PERTURBATION"))
    L.append("*STATIC")

    if given:
        # 步内重新声明同一个自由度即覆盖上面的零位移
        L.append("*BOUNDARY")
        fixity = {int(s["node"]): s["fix"] for s in model["supports"]}
        for nid in sorted(given):
            for k, value in enumerate(given[nid]):
                if value and fixity.get(nid, (0,) * 6)[k]:
                    L.append(" %d, %d, %d, %s" % (nid, k + 1, k + 1, _fmt(value)))

    if cload:
        L.append("*CLOAD")
        for e in cload:
            for k, value in enumerate(e["load"]):
                if value:
                    L.append(" %d, %d, %s" % (int(e["node"]), k + 1, _fmt(value)))

    if mload:
        L.append("*DLOAD")
        for e in mload:
            wx, wy, wz = (float(v) for v in e["w"])
            mag = float(np.linalg.norm([wx, wy, wz]))
            if mag == 0.0:
                continue
            # PZ/PX/PY 是全局方向的单位长度荷载，正好对应本程序的全局 w
            for comp, label in ((wx, "PX"), (wy, "PY"), (wz, "PZ")):
                if comp:
                    L.append(" E%d, %s, %s" % (int(e["member"]), label, _fmt(comp)))

    L.append("*NODE PRINT, NSET=ALLN, SUMMARY=NO")
    L.append(" U,")
    L.append("*NODE PRINT, NSET=ALLN, SUMMARY=NO")
    L.append(" RF,")
    L.append("*OUTPUT, FIELD")
    L.append("*NODE OUTPUT")
    L.append(" U, RF")
    L.append("*END STEP")

    path.write_text("\n".join(L) + "\n", encoding="ascii")
    return path


